### ISSUE TITLE
no breaking of symmetry

### ISSUE THREAD

**Issue by Mastercorp** [activatedgeek/LeNet-5#4]
Is there a reason you do not use the "real" LeNet, with the  breaking of symmetry? ( https://engmrk.com/lenet-5-a-classic-cnn-architecture/ , see Third Layer here )

**Comment by activatedgeek** [comment]
Sure thing. This was a decision only made for convenience as the network started achieving ~99% accuracy.

Feel free to update and I'd be happy to accept a PR.

**Comment by Mastercorp** [comment]
I was looking for an implementation of the "real" LeNet for some time, but i think people just dont use this "old" method. Even for small sizes of featuremaps ( 10 ), you would have to make a own conv layer for each mapping.
Sadly, i haven´t found any papers, which talk about the benefits or disadvantages of using such a "symmetry break".
